# Generated by Django 3.2.16 on 2023-02-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('product', models.CharField(blank=True, max_length=150)),
                ('ad_copy', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(blank=True, choices=[('Sent', 'Sent'), ('Pending', 'Pending')], max_length=50, null=True)),
            ],
        ),
    ]
